---
- name: Check if REX-Ray is installed
  command: dpkg-query -W rexray
  register: rexray_check_deb
  failed_when: rexray_check_deb.rc > 1
  changed_when: false

- name: Download REX-Ray .deb to local file
  get_url:
    url="{{ rexray_pkg_url }}/{{ rexray_channel }}/{{ rexray_version }}/rexray-{{ rexray_version }}-{{ ansible_architecture }}.deb"
    dest=/tmp
  when: rexray_check_deb.rc == 1

- name: Install REX-Ray .deb
  apt: deb="/tmp/rexray-{{ rexray_version }}-{{ ansible_architecture }}.deb" state=present
  when: rexray_check_deb.rc == 1

- name: Delete temporary file
  file: path="/tmp/rexray-{{ rexray_version }}-{{ ansible_architecture }}.deb" state=absent
  when: rexray_check_deb.rc == 1


- name: Create config file directory
  file: path=/etc/rexray state=directory mode=0755 owner=root group=root

- name: Add rexray config file
  template: src=rexray-conf.j2 dest=/etc/rexray/config.yml mode=0755 owner=root group=root
  notify: restart rexray

- name: ensure rexray is running
  service:
    name: rexray
    state: started

- name: Install dvdcli
  shell: curl -sSL https://dl.bintray.com/emccode/dvdcli/install | sh -

- name: Install mesos-module-dvdi
  get_url: dest=/usr/lib/libmesos_dvdi_isolator-{{mesos_version}}.so url=https://github.com/emccode/mesos-module-dvdi/releases/download/v{{mesos_module_dvdi_version}}/libmesos_dvdi_isolator-{{mesos_version}}.so mode=0777

- name: Configure mesos moduke dvdi
  template: src=dvdi-mod.j2 dest=/usr/lib/dvdi-mod.json
  notify:
    - Restart mesos-slave

