- name: create log directory  
  file: path={{ mesos_log_dir }} state=directory mode=0755
  tags:
    - mesos-master
    - mesos-slave

- name: create etc directory
  file: state=directory path=/etc/mesos
  tags: 
    - mesos-master
    - mesos-slave

- name: Include distribution-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_distribution|lower }}.yml"
    - "vars/{{ ansible_os_family|lower }}.yml"

- include: master.yml
  when: mesos_install_mode == "master"

- include: slave.yml
  when: mesos_install_mode == "slave"
