- name: create directory path to store the persistent information 
  file:
    path: "{{ mesos_master_work_dir }}"
    state: directory
    mode: 0755
  tags:
    - mesos-master

- name: "Create mesos container env file"
  template:
    src=mesos-master-env.j2 dest=/etc/mesos/.mesosmenv


- name: run mesos-master container
  docker_container:
    name: mesos-master
    image: "{{ mesos_master_image }}"
    detach: true
    state: started
    network_mode: "host"
    volumes:
    - "{{ mesos_master_work_dir }}:{{ mesos_master_work_dir }}"
    - "{{ mesos_log_dir }}:{{ mesos_log_dir }}"
    restart_policy: always
    env_file: /etc/mesos/.mesosmenv
  tags:
    - mesos-master
